name: Backend CI

on:
  push:
    paths:
      - 'backend/**' # Run workflow when backend files change
      - '.github/workflows/ci-backend.yml' # Run workflow when this pipeline changes
    branches: [ "main", "dev" ]
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'
    branches: [ "main", "dev" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend # Specify the working directory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release